/* Shared navigation, footer and cart count for the MH Websites company site. */
function renderHeader(activePage){
  const links=[{href:"index.html",label:"Home",key:"home"},{href:"services.html",label:"Services",key:"services"},{href:"solutions.html",label:"Solutions",key:"solutions"},{href:"shop.html",label:"Online Store",key:"shop"},{href:"about.html",label:"About",key:"about"},{href:"contact.html",label:"Contact",key:"contact"}];
  const navLinks=links.map(l=>`<a href="${l.href}" class="${activePage===l.key?'active':''}">${l.label}</a>`).join("");
  document.getElementById("site-header").innerHTML=`<div class="top-strip">DIGITAL SOLUTIONS · IT SUPPORT · TECHNOLOGY SUPPLIES</div><div class="header-bar container"><a href="index.html" class="logo" aria-label="MH Websites home"><span class="logo-mark">MH</span><span>MH WEBSITES<small>Digital Solutions &amp; Technology</small></span></a><nav class="main-nav" id="mainNav" aria-label="Main navigation">${navLinks}<a href="contact.html" class="nav-quote">Request a Quote</a></nav><div class="header-actions"><a href="cart.html" class="icon-btn cart-button" aria-label="View shopping cart">🛒<span class="cart-count" id="cartCount">0</span></a><button class="icon-btn nav-toggle" id="navToggle" aria-label="Open menu" aria-expanded="false">☰</button></div></div>`;
  const toggle=document.getElementById("navToggle");toggle.addEventListener("click",()=>{const nav=document.getElementById("mainNav");const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",open);toggle.textContent=open?"×":"☰";});updateCartCount();
}
function renderFooter(){document.getElementById("site-footer").innerHTML=`<div class="container footer-grid"><div><a href="index.html" class="logo"><span class="logo-mark">MH</span><span>MH WEBSITES<small>Digital Solutions &amp; Technology</small></span></a><p style="margin-top:18px">A South African technology company building useful digital solutions and supplying the tools businesses need to keep working.</p></div><div><h4>Services</h4><ul><li><a href="services.html#websites">Web development</a></li><li><a href="services.html#systems">Custom systems</a></li><li><a href="services.html#learning">Learning platforms</a></li><li><a href="services.html#data">Dashboards &amp; data</a></li></ul></div><div><h4>Explore</h4><ul><li><a href="solutions.html">Our solutions</a></li><li><a href="shop.html">Online store</a></li><li><a href="about.html">About MH Websites</a></li><li><a href="contact.html">Contact us</a></li></ul></div><div><h4>Get In Touch</h4><ul><li><a href="tel:+27698418354">+27 69 841 8354</a></li><li><a href="mailto:mhweb36@gmail.com">mhweb36@gmail.com</a></li><li>East London, Eastern Cape</li><li>Mon–Fri, 08:00–17:00</li></ul></div></div><div class="footer-bottom container"><span>© 2026 MH WEBSITES (PTY) LTD.</span><span>BUILT FOR SOUTH AFRICAN BUSINESS</span></div>`;}
function updateCartCount(){const cart=getCart();const count=cart.reduce((sum,item)=>sum+item.qty,0);const el=document.getElementById("cartCount");if(el)el.textContent=count;}
function showToast(message){let toast=document.getElementById("toast");if(!toast){toast=document.createElement("div");toast.id="toast";toast.className="toast";document.body.appendChild(toast);}toast.textContent=message;toast.classList.add("show");clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.remove("show"),2400);}
